package UI;

import javax.swing.*;
import java.awt.*;
import java.util.Objects;

/**
 *
 * @author lperf
 */
public class UISearchVaxCenterDialog extends javax.swing.JFrame{
     /**
      *
      * Creates new form ServerHomeUI
      */
        public UISearchVaxCenterDialog() {
            initComponents();
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">
        private void initComponents() {

            jPanel1 = new javax.swing.JPanel();
            jLabelNome = new javax.swing.JLabel();
            jLabelComune = new javax.swing.JLabel();
            jLabelQualificatore = new javax.swing.JLabel();
            jLabelVia = new javax.swing.JLabel();
            jLabelCivico = new javax.swing.JLabel();
            jLabelSigla = new javax.swing.JLabel();
            jLabelCAP = new javax.swing.JLabel();
            jLabelTipologia = new javax.swing.JLabel();
            jLabelicon = new javax.swing.JLabel();
            jLabelTitle = new javax.swing.JLabel();
            jLabelinsComune = new javax.swing.JLabel();
            jLabelinsQualificatore = new javax.swing.JLabel();
            jLabelinsVia = new javax.swing.JLabel();
            jLabelinsCivico = new javax.swing.JLabel();
            jLabelinsSigla = new javax.swing.JLabel();
            jLabelinsCAP = new javax.swing.JLabel();
            jLabelinsTipologia = new javax.swing.JLabel();
            jLabelinsNome = new javax.swing.JLabel();

            setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
            setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
            setFocusableWindowState(false);

            jPanel1.setBackground(new java.awt.Color(181, 226, 232));

            jLabelNome.setFont(new java.awt.Font("Segoe UI", 2, 30)); // NOI18N
            jLabelNome.setForeground(new java.awt.Color(0, 0, 153));
            jLabelNome.setText("Nome:");

            jLabelComune.setFont(new java.awt.Font("Segoe UI", 2, 30)); // NOI18N
            jLabelComune.setForeground(new java.awt.Color(0, 0, 153));
            jLabelComune.setText("Comune: ");

            jLabelQualificatore.setFont(new java.awt.Font("Segoe UI", 2, 30)); // NOI18N
            jLabelQualificatore.setForeground(new java.awt.Color(0, 0, 153));
            jLabelQualificatore.setText("Qualificatore:");

            jLabelVia.setFont(new java.awt.Font("Segoe UI", 2, 30)); // NOI18N
            jLabelVia.setForeground(new java.awt.Color(0, 0, 153));
            jLabelVia.setText("Via:");

            jLabelCivico.setFont(new java.awt.Font("Segoe UI", 2, 30)); // NOI18N
            jLabelCivico.setForeground(new java.awt.Color(0, 0, 153));
            jLabelCivico.setText("Civico:");

            jLabelSigla.setFont(new java.awt.Font("Segoe UI", 2, 30)); // NOI18N
            jLabelSigla.setForeground(new java.awt.Color(0, 0, 153));
            jLabelSigla.setText("Sigla:");

            jLabelCAP.setFont(new java.awt.Font("Segoe UI", 2, 30)); // NOI18N
            jLabelCAP.setForeground(new java.awt.Color(0, 0, 153));
            jLabelCAP.setText("CAP: ");

            jLabelTipologia.setFont(new java.awt.Font("Segoe UI", 2, 30)); // NOI18N
            jLabelTipologia.setForeground(new java.awt.Color(0, 0, 153));
            jLabelTipologia.setText("Tipologia:");

            //jLabelicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/guiproject/serverhomeui/My_project-1-removebg2.png"))); // NOI18N

            jLabelTitle.setFont(new java.awt.Font("Segoe Script", 3, 36)); // NOI18N
            jLabelTitle.setText("Centro Vaccinale");

            jLabelinsComune.setFont(new java.awt.Font("Sitka Small", 0, 24)); // NOI18N

            jLabelinsQualificatore.setFont(new java.awt.Font("Sitka Small", 0, 24)); // NOI18N

            jLabelinsVia.setFont(new java.awt.Font("Sitka Small", 0, 24)); // NOI18N

            jLabelinsCivico.setFont(new java.awt.Font("Sitka Small", 0, 24)); // NOI18N

            jLabelinsSigla.setFont(new java.awt.Font("Sitka Small", 0, 24)); // NOI18N

            jLabelinsCAP.setFont(new java.awt.Font("Sitka Small", 0, 24)); // NOI18N

            jLabelinsTipologia.setFont(new java.awt.Font("Sitka Small", 0, 24)); // NOI18N

            jLabelinsNome.setFont(new java.awt.Font("Sitka Small", 0, 24)); // NOI18N

            javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
            jPanel1.setLayout(jPanel1Layout);
            jPanel1Layout.setHorizontalGroup(
                    jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(46, 46, 46)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                            .addComponent(jLabelNome, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                            .addComponent(jLabelCivico, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                                    .addComponent(jLabelinsNome, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                    .addGap(0, 0, Short.MAX_VALUE))
                                                            .addComponent(jLabelinsCivico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                                    .addComponent(jLabelComune)
                                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                    .addComponent(jLabelinsComune, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                                    .addComponent(jLabelSigla)
                                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                    .addComponent(jLabelinsSigla, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                                    .addComponent(jLabelVia)
                                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                    .addComponent(jLabelinsVia, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                                    .addComponent(jLabelCAP)
                                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                    .addComponent(jLabelinsCAP, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                                    .addComponent(jLabelTipologia)
                                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                    .addComponent(jLabelinsTipologia, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                                    .addComponent(jLabelQualificatore)
                                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                    .addComponent(jLabelinsQualificatore, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                    .addGap(0, 15, Short.MAX_VALUE)))
                                    .addContainerGap())
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(jLabelicon)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabelTitle)
                                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );
            jPanel1Layout.setVerticalGroup(
                    jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addContainerGap()
                                                    .addComponent(jLabelicon, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addGap(56, 56, 56)
                                                    .addComponent(jLabelTitle)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabelNome)
                                            .addComponent(jLabelinsNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabelComune)
                                            .addComponent(jLabelinsComune, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabelQualificatore)
                                            .addComponent(jLabelinsQualificatore, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabelVia)
                                            .addComponent(jLabelinsVia))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabelCivico)
                                            .addComponent(jLabelinsCivico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabelSigla)
                                            .addComponent(jLabelinsSigla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabelCAP)
                                            .addComponent(jLabelinsCAP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabelTipologia)
                                            .addComponent(jLabelinsTipologia))
                                    .addContainerGap(100, Short.MAX_VALUE))
            );

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            );
            layout.setVerticalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            );

            pack();
        }// </editor-fold>

        /**
         * @param args the command line arguments
         */
        public static void main(String args[]) {
            /* Set the Nimbus look and feel */
            //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
            /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
             * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
             */
            try {
                for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                    if ("Nimbus".equals(info.getName())) {
                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                        break;
                    }
                }
            } catch (ClassNotFoundException ex) {
                java.util.logging.Logger.getLogger(UISearchVaxCenterDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (InstantiationException ex) {
                java.util.logging.Logger.getLogger(UISearchVaxCenterDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (IllegalAccessException ex) {
                java.util.logging.Logger.getLogger(UISearchVaxCenterDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                java.util.logging.Logger.getLogger(UISearchVaxCenterDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
            //</editor-fold>

            /* Create and display the form */
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    new UISearchVaxCenterDialog().setVisible(true);
                }
            });
        }

        // Variables declaration - do not modify
        private javax.swing.JLabel jLabelCAP;
        private javax.swing.JLabel jLabelCivico;
        private javax.swing.JLabel jLabelComune;
        private javax.swing.JLabel jLabelNome;
        private javax.swing.JLabel jLabelQualificatore;
        private javax.swing.JLabel jLabelSigla;
        private javax.swing.JLabel jLabelTipologia;
        private javax.swing.JLabel jLabelTitle;
        private javax.swing.JLabel jLabelVia;
        private javax.swing.JLabel jLabelicon;
        public javax.swing.JLabel jLabelinsCAP;
        public javax.swing.JLabel jLabelinsCivico;
        public javax.swing.JLabel jLabelinsComune;
        public javax.swing.JLabel jLabelinsNome;
        public javax.swing.JLabel jLabelinsQualificatore;
        public javax.swing.JLabel jLabelinsSigla;
        public javax.swing.JLabel jLabelinsTipologia;
        public javax.swing.JLabel jLabelinsVia;
        private javax.swing.JPanel jPanel1;
        // End of variables declaration
}




